import { InventoryItem, StockMovement, Category } from './types';

export const DEMO_ITEMS: InventoryItem[] = [
  {
    id: '1',
    name: 'Grilled Chicken Sandwich',
    sku: 'FOOD-GCS-001',
    category: 'Food',
    quantity: 50,
    minThreshold: 15,
    price: 45.00,
    location: 'Kitchen Fridge',
    lastUpdated: '2024-03-10T10:00:00Z',
    status: 'In Stock',
    expiryDate: '2024-03-16T18:00:00Z',
  },
  {
    id: '2',
    name: 'Intro to Economics Textbook',
    sku: 'BOOK-ECON-101',
    category: 'Books',
    quantity: 12,
    minThreshold: 10,
    price: 850.00,
    location: 'Section B-Shelf 4',
    lastUpdated: '2024-03-12T14:30:00Z',
    status: 'Low Stock',
  },
  {
    id: '3',
    name: 'UJ Branded Hoodie (Navy)',
    sku: 'APP-UJ-HD-NV',
    category: 'Apparel',
    quantity: 20,
    minThreshold: 5,
    price: 450.00,
    location: 'Display Rack 1',
    lastUpdated: '2024-03-11T09:15:00Z',
    status: 'In Stock',
  },
  {
    id: '4',
    name: 'Coke 500ml',
    sku: 'BEV-COKE-500',
    category: 'Beverages',
    quantity: 200,
    minThreshold: 48,
    price: 18.50,
    location: 'Main Cooler',
    lastUpdated: '2024-03-13T16:45:00Z',
    status: 'In Stock',
  },
  {
    id: '5',
    name: 'Scientific Calculator Casio',
    sku: 'STA-CASIO-FX',
    category: 'Stationery',
    quantity: 0,
    minThreshold: 3,
    price: 350.00,
    location: 'Security Counter',
    lastUpdated: '2024-03-14T11:20:00Z',
    status: 'Out of Stock',
  },
];

export const DEMO_MOVEMENTS: StockMovement[] = [
  {
    id: 'm1',
    itemId: '1',
    itemName: 'Grilled Chicken Sandwich',
    type: 'In',
    quantity: 20,
    date: '2024-03-10T10:00:00Z',
    reason: 'Restock from kitchen',
  },
  {
    id: 'm2',
    itemId: '2',
    itemName: 'Intro to Economics Textbook',
    type: 'Out',
    quantity: 5,
    date: '2024-03-12T14:30:00Z',
    reason: 'Student Purchase #UJ-102',
  },
];

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Food', count: 45 },
  { id: '2', name: 'Beverages', count: 32 },
  { id: '3', name: 'Books', count: 120 },
  { id: '4', name: 'Stationery', count: 200 },
  { id: '5', name: 'Apparel', count: 15 },
];
