import { InventoryItem, StockMovement, Category } from './types';

export const DEMO_ITEMS: InventoryItem[] = [
  {
    id: '1',
    name: 'Grilled Chicken Sandwich',
    sku: 'FOOD-GCS-001',
    category: 'Food',
    quantity: 50,
    minThreshold: 15,
    price: 45.00,
    location: 'Kitchen Fridge',
    lastUpdated: '2024-03-10T10:00:00Z',
    status: 'In Stock',
    expiryDate: '2024-03-16T18:00:00Z',
  },
  {
    id: '2',
    name: 'Fresh Garden Salad',
    sku: 'FOOD-SAL-002',
    category: 'Food',
    quantity: 12,
    minThreshold: 15,
    price: 35.00,
    location: 'Display Fridge A',
    lastUpdated: '2024-03-12T14:30:00Z',
    status: 'Low Stock',
    expiryDate: '2024-03-14T10:00:00Z',
  },
  {
    id: '3',
    name: 'Sparkling Mineral Water',
    sku: 'BEV-SPW-003',
    category: 'Beverages',
    quantity: 120,
    minThreshold: 30,
    price: 15.00,
    location: 'Cooler 2',
    lastUpdated: '2024-03-11T09:15:00Z',
    status: 'In Stock',
  },
  {
    id: '4',
    name: 'Coca-Cola 500ml',
    sku: 'BEV-COKE-500',
    category: 'Beverages',
    quantity: 200,
    minThreshold: 48,
    price: 18.50,
    location: 'Main Cooler',
    lastUpdated: '2024-03-13T16:45:00Z',
    status: 'In Stock',
  },
  {
    id: '5',
    name: 'Double Chocolate Muffin',
    sku: 'FOOD-MUF-004',
    category: 'Food',
    quantity: 0,
    minThreshold: 10,
    price: 25.00,
    location: 'Bakery Counter',
    lastUpdated: '2024-03-14T11:20:00Z',
    status: 'Out of Stock',
  },
  {
    id: '6',
    name: 'UJ Student Campus Mug',
    sku: 'APP-MUG-01',
    category: 'Apparel',
    quantity: 45,
    minThreshold: 10,
    price: 85.00,
    location: 'Merch Shelf',
    lastUpdated: '2024-03-10T11:20:00Z',
    status: 'In Stock',
  }
];

export const DEMO_MOVEMENTS: StockMovement[] = [
  {
    id: 'm1',
    itemId: '1',
    itemName: 'Grilled Chicken Sandwich',
    type: 'In',
    quantity: 20,
    date: '2024-03-10T10:00:00Z',
    reason: 'Restock from kitchen',
  },
  {
    id: 'm2',
    itemId: '2',
    itemName: 'Fresh Garden Salad',
    type: 'Out',
    quantity: 5,
    date: '2024-03-12T14:30:00Z',
    reason: 'Lunch Rush Sale',
  },
  {
    id: 'm3',
    itemId: '5',
    itemName: 'Double Chocolate Muffin',
    type: 'Out',
    quantity: 8,
    date: '2024-03-14T10:00:00Z',
    reason: 'Morning Rush Sale',
  }
];

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Food', count: 45 },
  { id: '2', name: 'Beverages', count: 32 },
  { id: '3', name: 'Books', count: 120 },
  { id: '4', name: 'Stationery', count: 200 },
  { id: '5', name: 'Apparel', count: 15 },
];
